### ISSUE TITLE
ModuleNotFoundError: No module named 'dateparser'

### ISSUE THREAD

**Issue by alexander-paterson** [ThePornDatabase/stash_theporndb_scraper#49]
I've pulled the latest update, ran the requirements.txt file.

When I run `python3 scrapeScenes.py` I'm getting the following error:

```
Traceback (most recent call last):
  File "/srv/dev-disk-by-label-data/users/alex/git/stash_theporndb_scraper/scrapeScenes.py", line 19, in <module>
    import StashInterface
  File "/srv/dev-disk-by-label-data/users/alex/git/stash_theporndb_scraper/StashInterface.py", line 8, in <module>
    import dateparser
ModuleNotFoundError: No module named 'dateparser'
```

**Comment by 4c0d3r** [comment]
The readme needs updated to reference:   "pip install requirements.txt -r"

**Comment by alexander-paterson** [comment]
If I run `pip install requirements.txt -r` I get the following message:

```
Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-r option requires 1 argument
```

If I try `pip install -r requirements.txt` I get this output

```
Requirement already satisfied: Pillow==9.0.0 in /srv/dev-disk-by-label-data/users/alex/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (9.0.0)
Requirement already satisfied: requests==2.27.1 in /srv/dev-disk-by-label-data/users/alex/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /srv/dev-disk-by-label-data/users/alex/.local/lib/python3.9/site-packages (from requests==2.27.1->-r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.27.1->-r requirements.txt (line 2)) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.27.1->-r requirements.txt (line 2)) (1.26.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.27.1->-r requirements.txt (line 2)) (2.10)
```

Then if I run `python3 scrapeScenes.py` I'm getting the same error as my initial post.

**Comment by DirtyRacer1337** [comment]
`pip install dateparser`

blame @Darklyter, he forgot update `requirements.txt`

**Comment by Darklyter** [comment]
That's fair
